config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :bases

  resources :users do
    collection { post :import }
    get 'attendance_user_index'
    member do
      get   'edit_basic_info'
      patch 'update_basic_info'
      # 1カ月分の変更申請
      get   'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      # 1カ月分の勤怠申請
      get   'attendances/edit_one_month_request'
      patch 'attendances/update_month_request'
    end
    resources :attendances, only: [:update] do
      member do
        # 残業申請
        get   'edit_overwork'
        patch 'update_overwork'
        # 残業承認
        get   'edit_overwork_notice'
        patch 'update_overwork_notice'
        # 勤怠承認
        get   'edit_attendance_change'
        patch 'update_attendance_change'
        # 1カ月分の承認
        get   'edit_one_month_approval'
        patch 'update_one_month_approval'
        # 勤怠ログ
        get   'log_page'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      # IDが見つかれば、レコードを呼び出し、見つからなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updateble_attributes)
      # 保存する
      user.save!(validate: false)
    end
  end

  # 更新を許可するカラムを定義
  def self.updateble_attributes
    ["name", "email", "department", "employee_number", "uid", "basic_work_time", 
      "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end

  def self.in_working_users
    in_working_users = Attendance.where(worked_on: Date.today, finished_at: nil).where.not(started_at: nil).pluck(:user_id).uniq

    where(id: in_working_users)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :logged_in_user, only: [:edit, :update]
  before_action :admin_or_correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :attendance_user_index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :other_user, only: :show
  before_action :set_one_month, only: :show
  before_action :not_allow_admin_user, only: :show
  
  def index
    @users = User.paginate(page: params[:page]).order("id ASC")
    @users = @users.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end
  
  def attendance_user_index
    @in_working_users = User.in_working_users
  end

  def import
    if params[:file].blank?
      flash[:danger] = 'ファイルを選択してください。'
      redirect_to users_url
    elsif File.extname(params[:file].original_filename) == ".csv"
      User.import(params[:file])
      flash[:success] = 'インポートしました。'
      redirect_to users_url
    else
      flash[:danger] = 'csvファイルのみ読み込み可能です。'
      redirect_to users_url
    end
  end

  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
    @superior = User.where(superior: true).where.not(id: @user.id)
    @attendance = @user.attendances.find_by(worked_on: @first_day)
    if current_user.superior?
      @overwork_sum = Attendance.includes(:user).where(superior_confirmation: current_user.id, overwork_status: "申請中").count
      @attendance_change_sum = Attendance.includes(:user).where(superior_attendance_change_confirmation: current_user.id, attendance_change_status: "申請中").count
      @one_month_approval_sum = Attendance.includes(:user).where(superior_month_notice_confirmation: current_user.id, one_month_approval_status: "申請中").count
    end
    # CSV出力
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_attendance_csv(@attendance)
      end
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit
    end

    
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end

  def update_basic_info
    @user = User.find(params[:id])
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  private
  
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:name, :email, :department, :employee_number, :uid, :basic_work_time, 
                                  :designated_work_start_time, :designated_work_end_time, :password)
    end

    def send_attendance_csv(attendances)
      # 文字化け防止
      bom = "\uFEFF"
      # CSV.genetateとは、対象データを自動的にCSV形式に変換してくれるCSVライブラリの一種
      csv_data = CSV.generate(bom, encoding: Encoding::SJIS, row_sep: "\r\n", force_quotes: true) do |csv|
        # %w()は、空白で区切って配列を返します。
        column_names = %w(日付 曜日 出社時間 退社時間)
        # csv << column_namesは表の列に入る名前を定義します。
        csv << column_names
        # column_valuesに代入するカラム値を定義します。
        @attendances = @user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
        @attendances.each do |day|
          column_values = [
            l(day.worked_on, format: :short),
            $days_of_the_week[day.worked_on.wday],
            if day.started_at.present?
              l(day.started_at.floor_to(60*15), format: :time)
            elsif (day.attendance_change_status == "承認").present?
              l(day.started_at.floor_to(60*15), format: :time)
            else
              ""
            end,
            if day.finished_at.present?
              l(day.finished_at.floor_to(60*15), format: :time)
            elsif (day.attendance_change_status == "承認").present?
              l(day.finished_at.floor_to(60*15), format: :time)
            else
              ""
            end
          ]
        # csv << column_valuesは表の行に入る値を定義します。
          csv << column_values
        end
      end
      # csv出力のファイル名を定義します。
      send_data(csv_data, filename: "勤怠一覧.csv")
    end
    
    # 管理権限者、または現在ログインしているユーザーを許可します。
    def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "権限がありません。"
        redirect_to(root_url)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '編集する') %>

<div class="row">
  <div class="col-md-12">
    <%= form_with(model: user, url: update_basic_info_user_path(user), local: true, method: :patch) do |f| %>
      <%= render 'shared/error_messages', object: user %>

      <%= f.label :name, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :email, class: "form-control" %>

      <%= f.label :department, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :department, class: "form-control" %>

      <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
      <%= f.number_field :employee_number, class: "form-control" %>

      <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :uid, class: "form-control" %>

      <%= f.label :password, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :password, class: "form-control" %>

      <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_work_time, class: "form-control" %>

      <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :designated_work_start_time, class: "form-control" %>

      <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :designated_work_end_time, class: "form-control" %>

      <%= f.submit "編集する", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/attendance_user_index.html.erb
<% provide(:title, 'Attendance Users') %>

<h1>出勤中社員一覧</h1>

<div class="col-md-12">
  <table class="table table-bordered table-hover table-working">
    <tr>
      <th><%= User.human_attribute_name :employee_number %></th>
      <th><%= User.human_attribute_name :name %></th>
    </tr>
    <% @in_working_users.each do |working_user| %>
      <tr>
        <td><%= working_user.employee_number %></td>
        <td><%= working_user.name %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, 'Edit Basic Info') %>

<h1>基本情報の更新</h1>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>

<% if params[:search].blank? %>
  <h1>全てのユーザー</h1>
<% else %>
  <h1>検索結果</h1>
<% end %>

<div class="row container">
  <div class="col-md-10 col-md-offset-9", id: "search-form">
    <h5>ユーザー名検索</h5>
    <%= form_with url: users_path, method: :get, local: true do |f| %>
      <%= f.text_field :search, placeholder: 'キーワードを入力...' %>
      <%= f.submit '検索', name: nil, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="row container">
  <div class="col-md-10">
    <%= form_tag import_users_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "CSVをインポート", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="col-md-12 all_users">
  <%= will_paginate %>
    <% @users.each do |user| %>
      <% if user.admin? %>
      <% else %>
        <%= user.name %>
        <br>|&nbsp;
        <%= link_to "削除", user, method: :delete, 
            data: { confirm: "削除してよろしいですか？" }, 
            class: "btn btn-primary" %>
            <br>
        <div class="panel-group">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h7 class="panel-title">
                <a data-toggle="collapse" href="#collapse<%= user.id %>" class="btn btn-primary btn-lg">編集</a>
              </h7>
            </div>
            <div id="collapse<%= user.id %>" class="panel-collapse collapse">
              <div class="panel-body">
                <%= render 'edit_basic_info', user: user %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <% if current_user?(@user) || current_user.admin? %>
        <td>
          <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
          &emsp;<%= l(@first_day, format: :middle) %>&emsp;時間管理表&emsp;
          <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
        </td>
      <% elsif %>
        <td><%= l(@first_day, format: :middle) %>&emsp;時間管理表</td>
      <% end %>
      <td>
        指定勤務開始時間&emsp;<%= l(@user.designated_work_start_time, format: :time) %><br>
        指定勤務終了時間&emsp;<%= l(@user.designated_work_end_time, format: :time) %>
      </td>
      <td colspan="3"><%= format_basic_info(@user.basic_work_time) %>&emsp;基本時間</td>
      <td>初日&emsp;<%= l(@first_day, format: :short) %></td>
    </tr>
    
    <tr>
      <td>所属&emsp;<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前&emsp;<%= @user.name %></td>
      <td>コード</td>
      <td></td>
      <td>出勤日数&emsp;<%= @worked_sum %>日</td>
      <td>締め&emsp;<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>
<div class="notice">
  <% if current_user.superior? && current_user?(@user) %>
      <!--所属長承認申請のお知らせ-->
    <div>
      <% if @one_month_approval_sum > 0 %>
        <%= link_to "【所属長承認申請のお知らせ】", edit_one_month_approval_user_attendance_path(@user), remote: true, class: "notice-superior" %>
        <span class="notice-border-superior"><%= "#{@one_month_approval_sum}件の通知があります。" %></span>
      <% else %>
        <%= "【所属長承認申請のお知らせ】" %>
      <% end %>
    </div>
      <!--勤怠変更申請のお知らせ-->
    <div>
      <% if @attendance_change_sum > 0 %>
        <%= link_to "【勤怠変更申請のお知らせ】", edit_attendance_change_user_attendance_path(@user), remote: true, class: "notice-superior" %>
        <span class="notice-border-superior"><%= "#{@attendance_change_sum}件の通知があります。" %></span>
      <% else %>
        <%= "【勤怠変更申請のお知らせ】" %>
      <% end %>
    </div>
      <!--残業申請のお知らせ-->
    <div>
      <% if @overwork_sum > 0 %>
        <%= link_to "【残業申請のお知らせ】", edit_overwork_notice_user_attendance_path(@user), remote: true, class: "notice-superior" %>
        <span class="notice-border-superior"><%= "#{@overwork_sum}件の通知があります。" %></span>
      <% else %>
        <%= "【残業申請のお知らせ】" %>
      <% end %>
    </div>
  <% end %>
</div>
<% if current_user?(@user) || current_user.admin? %>
  <div class="btn-users-show">
    <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
    <%= link_to "CSV出力", user_path(@user, date: @first_day, format: :csv), class: "btn btn-primary" %><br>
    <%= link_to "勤怠修正ログ（承認済）", log_page_user_attendance_path(@user), class: "btn btn-primary" %>
  </div>
<% end %>
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">所定外勤務</th>
      </tr>

      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>

      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <%
          css_class = 
          case $days_of_the_week[day.worked_on.wday]
            when '土'
              'text-primary'
            when '日'
              'text-danger'
            end
        %>
        <tr>
          <td>
            <% if current_user?(@user) || current_user.admin? %>
              <%= link_to "残業申請", edit_overwork_user_attendance_path(@user, day), remote: true, class: "btn btn-primary" %>
            <% end %>
          </td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= format_hour(day.started_at) if day.started_at.present? %></td>
          <td><%= format_min(day.started_at) if day.started_at.present? %></td>
          <td>
            <% if current_user?(@user) || current_user.admin? %>
              <% if btn_text = attendance_state(day) %>
                <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-block btn-attendance" %>
              <% end %>
            <% end %>
          </td>
          <td><%= format_hour(day.finished_at) if day.finished_at.present? %></td>
          <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes), day.next_day) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= day.overwork_end_time.strftime("%H") if day.overwork_end_time? %></td>
          <td><%= day.overwork_end_time.strftime("%M") if day.overwork_end_time? %></td>
          <td>
            <% if day.overwork_end_time.present? %>
              <%= working_overwork_times(@user.designated_work_end_time, day.overwork_end_time, day.overwork_next_day) %>
            <% end %>
          </td>
          <td><%= day.process_content %></td>
          <td>
            <% if day.overwork_status == "申請中" %>
              <%= User.find(day.superior_confirmation).name %>へ残業申請中<br>
            <% elsif (day.overwork_status == "承認") %>
              <%= User.find(day.superior_confirmation).name %>より残業<%= day.overwork_status %>済<br>
            <% elsif (day.overwork_status == "否認") %>
              <%= User.find(day.superior_confirmation).name %>より残業<%= day.overwork_status %><br>
            <% end %>
            <% if day.attendance_change_status == "申請中" %>
              <%= User.find(day.superior_attendance_change_confirmation).name %>へ勤怠変更申請中
            <% elsif (day.attendance_change_status == "承認") %>
              <%= User.find(day.superior_attendance_change_confirmation).name %>より勤怠編集<%= day.attendance_change_status %>済
            <% elsif (day.attendance_change_status == "否認") %>
              <%= User.find(day.superior_attendance_change_confirmation).name %>より勤怠編集<%= day.attendance_change_status %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan:横結合-->
      <tr>
        <td></td>
        <td colspan="2"></td>
        <td colspan="6"></td>
        <!--在社時間の合計-->
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="5"></td>
        <% if current_user?(@user) %>
          <td>
            <%= form_with(model: @attendance, url: attendances_update_month_request_user_path(@user), local: true, method: :patch) do |f| %>
              <%= f.hidden_field :one_month_approval_status, value: "申請中" %>
              <%= f.hidden_field :day, value: @first_day %>
                <% if @attendance.one_month_approval_status.nil? %>
                  所属長承認 未
                <% elsif @attendance.one_month_approval_status == "申請中" %>
                  <%= User.find(@attendance.superior_month_notice_confirmation).name %>へ勤怠申請中
                <% elsif @attendance.one_month_approval_status == "承認" || @attendance.one_month_approval_status == "否認" %>
                  <%= User.find(@attendance.superior_month_notice_confirmation).name %>より<%= @attendance.one_month_approval_status %>
                <% end %>
              <br><%= f.collection_select :superior_month_notice_confirmation, @superior, :id, :name,{prompt: ""}, {class: "form-control"} %>
              <%= f.submit " 申請 ", class: "btn btn-primary" %>
            <% end %>
          </td>
        <% end %>
      </tr>
    </tfoot>
  </table>
</div>

<!--モーダルウィンドウ表示-->
<div id="edit-overwork" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-overwork-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-attendance_change" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-one-month-approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>