config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :bases

  resources :users do
    collection { post :import }
    get 'attendance_user_index'
    member do
      get   'edit_basic_info'
      patch 'update_basic_info'
      # 1カ月分の変更申請
      get   'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      # 1カ月分の勤怠申請
      get   'attendances/edit_one_month_request'
      patch 'attendances/update_month_request'
    end
    resources :attendances, only: [:update] do
      member do
        # 残業申請
        get   'edit_overwork'
        patch 'update_overwork'
        # 残業承認
        get   'edit_overwork_notice'
        patch 'update_overwork_notice'
        # 勤怠承認
        get   'edit_attendance_change'
        patch 'update_attendance_change'
        # 1カ月分の承認
        get   'edit_one_month_approval'
        patch 'update_one_month_approval'
        # 勤怠ログ
        get   'log_page'
      end
    end
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }

  # 出社時間が存在しない場合、退社時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  # 出社・退社時間どちらも存在し、翌日チェックがない時、出社時間より早い退社時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  # 出社変更・退社変更時間どちらも存在し、翌日チェックがない時、出社変更時間より早い退社変更時間は無効
  validate :restarted_at_than_refinished_at_fast_if_invalid

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end

  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present? && !next_day.present?
      errors.add(:started_at, "より早い退勤時間は無効です。") if started_at > finished_at
    end
  end

  def restarted_at_than_refinished_at_fast_if_invalid
    if restarted_at.present? && refinished_at.present? && !next_day.present?
      errors.add(:started_at, "より早い退勤時間は無効です。") if restarted_at > refinished_at
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  include AttendancesHelper
  before_action :set_user, only: [:edit_one_month, :update_one_month, :edit_attendance_change, :update_attendance_change, :edit_overwork_notice, :update_month_request, :edit_one_month_approval]
  before_action :set_user_user_id, only: [:update_overwork_notice, :update_one_month_approval, :log_page]
  before_action :logged_in_user, only: [:update, :edit_one_month, :log_page]
  before_action :set_attendance, only: [:update, :edit_overwork, :update_overwork, :edit_overwork_notice, :log_page]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :other_user, only: [:edit_one_month, :update_one_month, :edit_overwork_notice]
  before_action :set_superior, only: [:edit_one_month, :update_one_month, :edit_overwork, :update_overwork, :update_month_request]
  before_action :set_one_month, only: [:edit_one_month, :edit_attendance_change, :edit_overwork_notice, :log_page]
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  # 勤怠変更
  def edit_one_month
  end
  
  def update_one_month
    a_count = 0
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item|
        if item[:superior_attendance_change_confirmation].present?
          if item[:refinished_at].blank? && item[:restarted_at].present?
            flash[:danger] = "退社時間が必要です。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
          elsif item[:restarted_at].blank? && item[:refinished_at].present?
            flash[:danger] = "出社時間が必要です。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
          end
          attendance = Attendance.find(id)
          attendance.attendance_change_status = "申請中"
          a_count += 1
          attendance.update_attributes!(item)
        end
      end
    end
    if a_count > 0
      flash[:success] = "勤怠編集を#{a_count}件、申請しました。"
      redirect_to user_url(date: params[:date]) and return
    else
      flash[:info] = "勤怠編集はありません。"
      redirect_to user_url(date: params[:date]) and return
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
  end

  # 勤怠変更の承認
  def edit_attendance_change
    @change_attendances = Attendance.where(superior_attendance_change_confirmation: @user.id, attendance_change_status: "申請中").order(:user_id, :worked_on).group_by(&:user_id)
  end

  def update_attendance_change
    attendance_change_params.each do |id, item|
      attendance = Attendance.find(id)
      if item[:change_check]
        if item[:attendance_change_status] == "承認"
          if attendance.begin_started.blank? && attendance.begin_finished.blank?
            attendance.begin_started = attendance.started_at
            attendance.begin_finished = attendance.finished_at
          end
          attendance.started_at = attendance.restarted_at
          attendance.finished_at = attendance.refinished_at
          attendance.note = attendance.note
        elsif item[:attendance_change_status] == "否認"
          if attendance.started_at.blank? && attendance.finished_at.blank?
            attendance.started_at = nil
            attendance.finished_at = nil
            attendance.note = nil
            attendance.restarted_at = nil
            attendance.refinished_at = nil
          else
            attendance.started_at = attendance.started_at
            attendance.finished_at = attendance.finished_at
            attendance.restarted_at = attendance.started_at
            attendance.refinished_at = attendance.finished_at
          end
        elsif item[:attendance_change_status] == "なし"
          attendance.started_at = nil
          attendance.finished_at = nil
          attendance.note = nil
          item[:attendance_change_status] = nil
        end
        item[:change_check] = nil
        attendance.update(item)
        flash[:success] = "勤怠変更申請の承認結果を送信しました。"
      end
    end
    redirect_to user_url(@user)
  end

  # 残業申請
  def edit_overwork
    @user = User.find(params[:user_id])
  end

  def update_overwork
    @user = User.find(params[:user_id])
    if overwork_params[:superior_confirmation].present? && overwork_params[:overwork_end_time].present?
      @attendance.update(overwork_params)
      flash[:success] = "#{@user.name}の残業を申請しました。"
    elsif overwork_params[:superior_confirmation].blank? && overwork_params[:overwork_end_time].present?
      flash[:danger] = "所属長を選択してください。"
    elsif overwork_params[:superior_confirmation].present? && overwork_params[:overwork_end_time].blank?
      flash[:danger] = "終了予定時間を入力してください。"
    end
    redirect_to user_url(@user)
  end

  # 残業申請の承認
  def edit_overwork_notice
    @user = User.find(params[:id])
    @overwork_attendances = Attendance.where(superior_confirmation: @user.id, overwork_status: "申請中").order(:user_id, :worked_on).group_by(&:user_id)
  end

  def update_overwork_notice
    overwork_notice_params.each do |id, item|
      attendance = Attendance.find(id)
      if item[:is_check]
        if item[:overwork_status] == "なし"
          attendance.overwork_end_time = nil
          attendance.superior_confirmation = nil
          item[:overwork_status] = nil
          item[:is_check] = nil
        end
        attendance.update(item)
        flash[:success] = "残業申請の承認結果を送信しました。"
      else
        flash[:danger] = "承認確認のチェックを入れてください。"
      end
    end
    redirect_to user_url(@user)
  end

  # １か月分の勤怠申請
  def edit_month_request
  end

  def update_month_request
    @attendance = @user.attendances.find_by(worked_on: params[:attendance][:day])
    if month_request_params[:superior_month_notice_confirmation].present?
      @attendance.update(month_request_params)
      flash[:success] = "#{@user.name}の１か月分の申請をしました。"
    else
      flash[:danger] = "所属長を選択してください。"
    end
    redirect_to user_url(@user)
  end

  # １か月分の勤怠所属長承認
  def edit_one_month_approval
    @month_attendances = Attendance.where(superior_month_notice_confirmation: @user.id, one_month_approval_status: "申請中").order(:user_id, :worked_on).group_by(&:user_id)
  end

  def update_one_month_approval
    month_approval_params.each do |id, item|
      attendance = Attendance.find(id)
      if item[:approval_check]
        if item[:one_month_approval_status] == "なし"
          item[:one_month_approval_status] = nil
          item[:approval_check] = nil
        end
        attendance.update(item)
        flash[:success] = "勤怠申請の承認結果を送信しました。"
      else
        flash[:danger] = "承認確認のチェックを入れてください。"
      end
    end
    redirect_to user_url(@user)
  end

  # 勤怠ログ
  def log_page
    if Attendance.where(one_month_approval_status: "承認").order(:user_id, :worked_on).group_by(&:user_id)
      if params["select_year(1i)"].nil?
        @first_day = Date.current.beginning_of_month
      else
        @first_day = Date.parse("#{params["select_year(1i)"]}/#{params["select_month(2i)"]}/1")
      end
      @last_day = @first_day.end_of_month
      @attendances = @user.attendances.where(worked_on: @first_day..@last_day, attendance_change_status: "承認").order(:worked_on)
    end
  end

  private

    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    def set_superior
      @superior = User.where(superior:true).where.not(id:current_user.id)
    end

    def attendances_params
      params.require(:user).permit(attendances: [:restarted_at, :refinished_at, :next_day, :note,
                                                :superior_attendance_change_confirmation,
                                                :attendance_change_status])[:attendances]
    end

    def attendance_change_params
      params.require(:user).permit(attendances: [:change_check, :attendance_change_status])[:attendances]
    end

    def overwork_params
      params.require(:attendance).permit(:overwork_end_time, :overwork_next_day, :process_content, :superior_confirmation, :overwork_status)
    end

    def overwork_notice_params
      params.require(:user).permit(attendances: [:is_check, :overwork_status])[:attendances]
    end

    def month_request_params
      params.require(:attendance).permit(:superior_month_notice_confirmation, :one_month_approval_status)
    end

    def month_approval_params
      params.require(:user).permit(attendances: [:approval_check, :one_month_approval_status])[:attendances]
    end
    
    # beforeフィルター
    
    # 管理権限者、または現在ログインしているユーザーを許可します。
    def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    false
  end
  
  
  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish, next_day)
    if next_day && (start >= finish)
      format("%.2f", (((finish - start) / 60) / 60.0) + 24)
    else
      format("%.2f", (((finish - start) / 60) / 60.0))
    end
  end
  
  def format_hour(time)
    format("%.d", (time.hour))
  end
  
  def format_min(time)
    format("%.2d", (((time.min) / 15) * 15))
  end
  
  # 不正な値があるか確認する
  def attendances_invalid?
    attendances = true
    attendances_params.each do |id, item|
      if item[:started_at].blank? && item[:finished_at].blank?
        next
      elsif item[:started_at].blank? || item[:finished_at].blank?
        attendances = false
        break
      elsif item[:started_at] > item[:finished_at]
        attendances = false
        break
      end
    end
    return attendances
  end

  def working_overwork_times(designated_work_end_time, overwork_end_time, overwork_next_day)
    if overwork_next_day
      format("%.2f", (overwork_end_time.hour - designated_work_end_time.hour) + ((overwork_end_time.min - designated_work_end_time.min) / 60.0) + 24)
    else
      format("%.2f", (overwork_end_time.hour - designated_work_end_time.hour) + ((overwork_end_time.min - designated_work_end_time.min) / 60.0))
    end
  end

  # 勤怠変更申請のステータス
  def attendance_change_status_text(status)
    case status
    when "申請中"
      "申請中"
    when "否認"
      "勤怠変更否認"
    when "承認"
      "勤怠変更承認済"
    when "なし"
    else
    end
  end

  # 残業申請のステータス
  def overwork_status_text(status)
    case status
    when "申請中"
      "申請中"
    when "否認"
      "残業否認"
    when "承認"
      "残業承認済"
    when "なし"
      "残業なし"
    else
    end
  end

  # １か月分の申請のステータス
  def one_month_approval_status_text(status)
    case status
    when "申請中"
      "１か月分の勤怠申請中"
    when "否認"
      "１か月分の勤怠否認"
    when "承認"
      "勤怠変更承認"
    when "なし"
    else
    end
  end
end

app/views/attendances/_edit_attendance_change.html.erb
<% provide(:title, 'edit^attendance-change') %>

<div class="modal-dialog modal-lg modal-dialog-cernter">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: update_attendance_change_user_attendance_path(@user), local: true, method: :patch) do |f| %>
        <% @change_attendances.each do |id, attendances| %>
          <h1 class="modal-title">【<%= User.find(id).name %>からの勤怠変更申請】</h1>
          <table class="tabla table-bordered table-condensed table-hover" id="modal-attendances">
            <thead>
              <tr>
                <th rowspan="3">日付</th>
                <th rowspan="3">曜日</th>
                <th colspan="4">変更前</th>
                <th colspan="4">変更後</th>
                <th rowspan="3">備考</th>
                <th rowspan="3">指示者確認㊞</th>
                <th rowspan="3">変更</th>
                <th rowspan="3">勤怠を確認する</th>
              </tr>
              <tr>
                <th colspan="2">出社</th>
                <th colspan="2">退社</th>
                <th colspan="2">出社</th>
                <th colspan="2">退社</th>
              </tr>
              <tr>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
              </tr>
            </thead>
            <tbody>
              <% attendances.each do |day| %>
                <%= f.fields_for "attendances[]", day do |attendance| %>
                  <tr>
                    <td><%= l(day.worked_on, format: :short) %></td>
                    <td><%= $days_of_the_week[day.worked_on.wday] %></td>
                    <!--変更前・出社-->
                    <td><%= day.started_at.strftime("%H") if day.started_at.present? %></td>
                    <td><%= day.started_at.strftime("%M") if day.started_at.present? %></td>
                    <!--変更前・退社-->
                    <td><%= day.finished_at.strftime("%H") if day.finished_at.present? %></td>
                    <td><%= day.finished_at.strftime("%M") if day.finished_at.present? %></td>
                    <!--変更後・出勤-->
                    <td><%= day.restarted_at.strftime("%H") if day.restarted_at.present? %></td>
                    <td><%= day.restarted_at.strftime("%M") if day.restarted_at.present? %></td>
                    <!--変更後・退社-->
                    <td><%= day.refinished_at.strftime("%H") if day.refinished_at.present? %></td>
                    <td><%= day.refinished_at.strftime("%M") if day.refinished_at.present? %></td>
                    <td><%= day.note %></td>
                    <td><%= attendance.select :attendance_change_status, [["",""], ["なし","なし"], ["申請中","申請中"], ["承認","承認"],["否認","否認"]], class: "form-control" %></td>
                    <td><%= attendance.check_box :change_check, {}, true, false %></td>
                    <td><%= link_to "確認", user_path(id, date: day.worked_on.beginning_of_month), target: :_blank, rel: "noopener noreferrer", class: "btn btn-primary" %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        <% end %>
        <div class="center">
          <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary btn-attendance-change" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/_edit_one_month_approval.html.erb
<% provide(:title, 'edit-one-month-approval') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>      
    </div>    
    <div class="modal-body">
      <%= form_with(model: @user, url: update_one_month_approval_user_attendance_path(@user), local: true, method: :patch) do |f| %>
        <% @month_attendances.each do |id, attendances| %>
          <h1 class="modal-title">【<%= User.find(id).name %>からの1ヶ月分勤怠申請】</h1>
          <table class="table table-bordered table-condensed table-hover" id="table-attendances">            
            <thead>
              <tr>
                <th>月</th>               
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
            <tbody>
              <% attendances.each do |day| %>              
                <%= f.fields_for "attendances[]", day do |attendance| %>                                  
                  <tr>
                    <td><%= day.worked_on.month %>月</td>                    
                    <td><%= attendance.select :one_month_approval_status,  [["",""],["なし","なし"], ["申請中","申請中"], ["承認","承認"], ["否認","否認"]], class: "form-control" %></td>
                    <td><%= attendance.check_box :approval_check, {}, true, false %></td>
                    <td><%= link_to "確認", user_path(id, date: day.worked_on.beginning_of_month), target: :_blank, rel: "noopener noreferrer", class: "btn btn-primary btn-sm" %>
                    </td>
                  </tr>
                <% end %>
              <% end %>                                
            </tbody>           
          </table> 
          <div class="center">        
            <%= f.submit "変更を送信", class: "btn btn-lg btn-primary" %>
          </div>
        <% end %>      
      <% end %>  
    </div>
  </div>
</div>

app/views/attendances/_edit_overwork.html.erb
<% provide(:title, 'edit-overwork') %>

<div class="modal-dialog modal-lg modal-dialog-cernter">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <h1 class="modal-title">【残業申請】</h1>
      <%= form_with(model: @attendance, url: update_overwork_user_attendance_path, local: true, method: :patch) do |f| %>
      <%= f.hidden_field :overwork_status, value: "申請中" %>
        <table class="tabla table-bordered table-condensed table-hover" id="modal-overwork">
          <thead>
            <tr>
              <th>日付</th>
              <th>曜日</th>
              <th>終了予定時間</th>
              <th>翌日</th>
              <th>業務処理内容</th>
              <th>指示者確認㊞</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= l(@attendance.worked_on, format: :short) %></td>
              <td><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
              <td><%= f.time_field :overwork_end_time, class: "form-control" %></td>
              <td><%= f.check_box :overwork_next_day, id: "overwork_next_day" %></td>
              <td><%= f.text_field :process_content, class: "form-control" %></td>
              <td>
                <%= f.collection_select :superior_confirmation, @superior, :id, :name,{prompt: ""}, {class: "form-control"} %>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="center">
          <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary btn-overwork" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/_edit_overwork_notice.html.erb
<% provide(:title, 'edit-overwork-notice') %>

<div class="modal-dialog modal-lg modal-dialog-cernter">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: update_overwork_notice_user_attendance_path(@user), local: true, method: :patch) do |f| %>
        <% @overwork_attendances.each do |id, attendances| %>
          <h1 class="modal-title">【<%= User.find(id).name %>からの残業申請】</h1>
          <table class="tabla table-bordered table-condensed table-hover" id="modal-overwork">
            <thead>
              <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>指定終了予定時間</th>
                <th>時間外時間</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
            <tbody>
              <% attendances.each do |day| %>
                <%= f.fields_for "attendances[]", day do |attendance| %>
                  <tr>
                    <td><%= l(day.worked_on, format: :short) %></td>
                    <td><%= $days_of_the_week[day.worked_on.wday] %></td>
                    <td><%= l(day.overwork_end_time, format: :time) if day.overwork_end_time? %></td>
                    <td><%= l(User.find(id).designated_work_end_time, format: :time) %></td>
                    <td>
                      <% if day.overwork_end_time.present? %>
                        <%= working_overwork_times(User.find(id).designated_work_end_time, day.overwork_end_time, day.overwork_next_day) %>
                      <% end %>
                    </td>
                    <td><%= day.process_content %></td>
                    <td><%= attendance.select :overwork_status, [["なし","なし"], ["申請中","申請中"], ["承認","承認"],["否認","否認"]], class: "form-control" %></td>
                    <td><%= attendance.check_box :is_check, {}, true, false %></td>
                    <td><%= link_to "確認", user_path(id, date: day.worked_on.beginning_of_month), target: :_blank, rel: "noopener noreferrer", class: "btn btn-primary" %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        <% end %>
        <div class="center">
          <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary btn-overwork" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/edit_attendance_change.js.erb
$("#edit-attendance_change").html("<%= escape_javascript(render 'edit_attendance_change') %>");
$("#edit-attendance_change").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @firstday), local: true, method: :patch) do |f| %>
  <div>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認㊞</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%
          css_class = 
          case $days_of_the_week[day.worked_on.wday]
            when '土'
              'text-primary'
            when '日'
              'text-danger'
            end
          %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
              <% if Date.current < day.worked_on %>
                <td><%= attendance.time_field :restarted_at, readonly: true, class: "form-control" %></td>
                <td><%= attendance.time_field :refinished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= attendance.time_field :restarted_at, class: "form-control" %></td>
                <td><%= attendance.time_field :refinished_at, class: "form-control" %></td>
              <% end %>
              <td><%= attendance.check_box :next_day, id: "next_day" %></td>
              <td>
                <% if day.restarted_at.present? && day.refinished_at.present? %>
                  <%= str_times = working_times(day.restarted_at, day.refinished_at, day.next_day) %>
                  <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
                <% end %>
              </td>
              <td><%= attendance.text_field :note, class: "form-control" %></td>
              <td>
                <% if day.attendance_change_status == "承認" %>
                  <%= attendance.collection_select :superior_attendance_change_confirmation, @superior, :id, :name, {include_blank: true, select: ""}, {class: "form-control"} %>
                <% elsif day.attendance_change_status == "申請中" %>
                  <%= attendance.collection_select :superior_attendance_change_confirmation, @superior, :id, :name, {include_blank: true, select: ""}, {class: "form-control"} %>
                <% else %>
                  <%= attendance.collection_select :superior_attendance_change_confirmation, @superior, :id, :name, {include_blank: true, selected: ""}, {class: "form-control"} %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/attendances/edit_one_month_approval.js.erb
$("#edit-one-month-approval").html("<%= escape_javascript(render 'edit_one_month_approval') %>");
$("#edit-one-month-approval").modal("show");

app/views/attendances/edit_overwork.js.erb
$("#edit-overwork").html("<%= escape_javascript(render 'edit_overwork') %>");
$("#edit-overwork").modal("show");

app/views/attendances/edit_overwork_notice.js.erb
$("#edit-overwork-notice").html("<%= escape_javascript(render 'edit_overwork_notice') %>");
$("#edit-overwork-notice").modal("show");

app/views/attendances/log_page.html.erb
<% provide(:title, 'log-page') %>

<h1>勤怠ログ</h1>

<%= form_with(url: log_page_user_attendance_path, local: true, method: :get) do |f| %>
  
  <tr>
    <td><%= f.date_select :select_year, {discard_month: "true", selected: @first_day}, class: "seach-date" %></td>
  </tr>
  <tr>
    <td><%= f.date_select :select_month, {discard_year: "true", discard_day: "true", selected: @first_day}, class: "seach-date" %></td>
  </tr>
  <br><%= f.submit "検索", class: "btn btn-md btn-primary" %>
<% end %>
<table class="table table-bordered table-condensed table-hover", id="table-attendances">
  <thead>
    <tr>
      <th>日付</th>
      <th>変更前出社時間</th>
      <th>変更前退社時間</th>
      <th>変更後出社時間</th>
      <th>変更後退社時間</th>
      <th>指示者</th>
      <th>承認日</th>
    </tr>
  </thead>
  <tbody>
    <% @attendances.each do |day| %>
      <tr>
        <td><%= day.worked_on.strftime("%Y-%m-%d") %></td>
        <td><%= day.begin_started.strftime("%R") if day.begin_started.present? %></td>
        <td><%= day.begin_finished.strftime("%R") if day.begin_finished.present? %></td>
        <td><%= day.started_at.strftime("%R") if day.started_at.present? %></td>
        <td><%= day.finished_at.strftime("%R") if day.finished_at.present? %></td>
        <td><%= User.find(day.superior_attendance_change_confirmation).name %></td>
        <td><%= day.updated_at.strftime("%Y-%m-%d") %></td>
      </tr>
    <% end %>
  </tbody>
</table>